#!/usr/bin/env python3

string = "ATGTGCCTTCAGACTTTAAACTTTGGAAATGGATTTGCTTTGGCTCTCTGCTTATCTTTTTTGCCAAATACTGATGTACCAATATTAGCATGTGGCAATGATGATTGCAGAATTCACATATTTGCTCAACAAAATGATCAGTTTCAGAAAGTGCTTTCTCTCTGTGGACATG"
string = string.replace("\n", "")
print(string)
print(len(string))